### ISSUE TITLE
1. házi feladat kész

### ISSUE THREAD

**Issue by nemethdav** [Teaching-projects/SOE-SZTA-2021-Sasok#2]
@hegyhati A kiadot feladattal elkészültünk, legyen szíves ellenőrizze le.

**Comment by hegyhati** [comment]
Meglestem, kb jo, de:

 - Unite != Unit :-) 
 - defense-rol en egy szot sem szoltam
 - Azt latom, hogy halottat nem utunk meg. Es zombik tudnak utni?
 - az `isAlive`-ot azert szerintem 1 sorban is el tudnank intezni :-)
 - ami lehet final, az legyen final

**Comment by nemethdav** [comment]
@hegyhati készen vagyunk a javításokkal, legyen szíves nézze meg újra a feladatot.

**Comment by hegyhati** [comment]
- a `dmg` nem final
 - `isAlive` meg mindig feleslegesen bonyolitott

**Comment by nemethdav** [comment]
@hegyhati kijavítottuk a kéréseket. Légyszíves nézd át újra.

**Comment by hegyhati** [comment]
Egy aprosag, attackban `-=` atlathatobba teszi a kodot. Ha ez megvan, csinalom amit beszeltunk.

**Comment by hegyhati** [comment]
ok
